// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7otkgpzudEV3uUxaTencr6mtCFt4LAxk',
    appId: '1:304521590369:web:306c5fe92070d4944ddc20',
    messagingSenderId: '304521590369',
    projectId: 'login-aaccc',
    authDomain: 'login-aaccc.firebaseapp.com',
    storageBucket: 'login-aaccc.appspot.com',
    measurementId: 'G-DZS7EM896K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pdgf_UVJdEaoFaaB6B0pRRGkf7eMOa8',
    appId: '1:304521590369:android:beb69537ac08c3054ddc20',
    messagingSenderId: '304521590369',
    projectId: 'login-aaccc',
    storageBucket: 'login-aaccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHhA0Th_D_SEpUOKb_gCMHtPaBw1qnyV8',
    appId: '1:304521590369:ios:452abd0eed91af1d4ddc20',
    messagingSenderId: '304521590369',
    projectId: 'login-aaccc',
    storageBucket: 'login-aaccc.appspot.com',
    iosClientId: '304521590369-t41c7khqflvjqsonab2ebv15or3a6al3.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleauthproject',
  );
}
